name: Deploy EKS

on:
  push:
    branches: feature/eks

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::915204716339:role/Testing-EKS
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run : terraform plan
      - run: terraform apply -auto-approve
